### ISSUE TITLE
Software Output

### ISSUE THREAD

**Issue by abhiyerra** [opszero/parkingspot#7]
# Observation

Create output for different software

# Expected Result

Have generators that use ParkingSpot to generate output to be used by different software that needs to access cheap computing.

# Why

It is a good way of making output that could be useful for using Spot Instances from within other instance types.

# Blog Post

- [ ] Tell a story of the use case. Put yourself in the buyer's shoes
- [ ] The dilemma that the team sought to solve for its prospects or customers
- [ ] How are we solving it?
- [ ] What does it look like?
- [ ] How to use it?
- [ ] Reiterate the value prop

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

- [ ] Write Kops output
- [ ] Write Terraform output

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Weebly
 - [ ] Post on Product Hunt as New Features / Screenshots
 - [ ] Send to Marketing Locations
